backend:
  name: github
  repo: ryanfiller/style-tile-test
  branch: master

  dispay_url: https://pedantic-cabbages.netlify.com/

media_folder: static/images/
public_folder: images/

collections:
  - name: sites
    label: Site Style
    folder: src/content/
    create: true
    fields:
      - { name: title, label: Title }
      - { name: url, label: Beta Link }
      - { name: favicon, label: Favicon, widget: image }
      - { name: notes, label: Notes, widget: "markdown"}
      - { name: logo, label: Logo, widget: image }
      - label: Colors
        name: colors
        widget: list
        field: {
            name: color, label: Color, widget: color
          }
      - { name: font, label: Fonts }
      - { name: paragraph-styles, label: Parangraph Styles }
      - { name: links-styles, label: Links Styles }
      - { name: list-styles, label: List Styles }
      - { name: block-quote-styles, label: Block Quote Styles }
      - { name: header-styles, label: Header Styles }



      # - { name: codepens, label: Code Pens }

# black / white

# colors (addable)
#     - color
#     - color
#     - color

# grays (addable)
#     - gray
#     - gray

# button
#     - button
#     - hover

# social icons (choosable)

# forms

# additional svgs
