backend:
  name: github
  repo: ryanfiller/style-tile-test
  branch: master

  dispay_url: https://pedantic-cabbages.netlify.com/

media_folder: static/images/
public_folder: images/

collections:
  - name: sites
    label: Site Style
    folder: src/content/
    create: true
    fields:
      - { name: title, label: Title, required: false }
      - { name: url, label: Beta Link, required: false }
      - { name: favicon, label: Favicon, widget: image, required: false }
      - { name: logo, label: Logo, widget: image, required: false }
      - label: Colors
        name: colors
        widget: list
        fields:
          - { name: color-name, label: Name }
          - { name: color, label: Color, widget: color }
        required: false
      - { name: font, label: Fonts, required: false }
      - { name: paragraph-styles, label: Parangraph Styles, required: false }
      - { name: links-styles, label: Links Styles, required: false }
      - { name: list-styles, label: List Styles, required: false }
      - { name: block-quote-styles, label: Block Quote Styles, required: false }
      - { name: header-styles, label: Header Styles, required: false }
      - { name: notes, label: Notes, widget: markdown, required: false}



      # - { name: codepens, label: Code Pens }

# black / white

# colors (addable)
#     - color
#     - color
#     - color

# grays (addable)
#     - gray
#     - gray

# button
#     - button
#     - hover

# social icons (choosable)

# forms

# additional svgs
