backend:
  name: github
  repo: ryanfiller/style-tile-test
  branch: master

  dispay_url: https://pedantic-cabbages.netlify.com/

media_folder: static/images/
public_folder: images/

collections:
  - name: sites
    label: Site Style
    folder: src/content/
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }